### ISSUE TITLE
React 15.5+ deprecates PropTypes and createClass

### ISSUE THREAD

**Issue by cwardzala** [seethroughtrees/react-wufoo-embed#4]
As of React 15.5 `React.PropTypes` and `React.createClass` are deprecated. react-wufoo-embed should move to [prop-types](https://www.npmjs.com/package/prop-types) and ES6 classes. Also the examples are out of date with React and should now be updated to use ReactDOM to render the `Wufoo` example.

**Comment by cwardzala** [comment]
#5 Fixes this.

**Comment by seethroughtrees** [comment]
Thanks so much for doing this @cwardzala .  Really happy to update this on npm as well.

**Comment by seethroughtrees** [comment]
https://www.npmjs.com/package/react-wufoo-embed bumped to major release to start using semver.

Thanks again.
